# Generated by Django 3.2.4 on 2021-06-25 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='type',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat')], default='dog', max_length=50),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(choices=[('rottweiler', 'Rottweiler'), ('bulldog', 'Bulldog')], max_length=50),
        ),
    ]
